## List

In [ ]:
# python list
a = list()
# a = []
print(a)
a = [1,2,3]
print(a)

[]
[1, 2, 3]


In [ ]:
# list operation - slicing
a = [1,2,3,4,5,6]
#    0 1 2 3 4 5
# a[start:end:step]
a[1:6:2]

[2, 4, 6]

In [ ]:
# list operation - insertion (2)
a = []
a.append(1)
a.append(2)
a.append(3)
a.insert(1,4)
print(a)

[1, 4, 2, 3]


In [ ]:
# list operation - deletion
a = [1, 4, 2, 3]
print(a)
# del a[1]
# item = a.pop(0)
a.remove(2)
# print(item)
print(a)


[1, 4, 2, 3]
[1, 4, 3]


## Dictionary

In [ ]:
[1 ,2, 3, 4]
0 --> 1
1 --> 2
...
...
{key1: value1, key2: value2}
key1 --> value1
key2 --> value2
...
...

In [ ]:
# initializing a ditionary
d = {"Eng": 96, "Math": 97, "CS": 99}
# d = dict()
print(d["CS"])

99


In [ ]:
# keys
print(d.keys())

dict_keys(['Eng', 'Math', 'CS'])


In [ ]:
# values
print(d.values())

dict_values([96, 97, 99])


In [ ]:
# items
print(d.items())

dict_items([('Eng', 96), ('Math', 97), ('CS', 99)])


# Numpy

In [ ]:
import numpy as np

In [ ]:
# creating a numpy array
# discuss types
# arr = np.array([1,2,3])
arr = np.array([1,2,3])
arr2 = arr.astype("S")
print(arr.dtype)
print(arr)
print(arr2.dtype)
print(arr2)

int64
[1 2 3]
|S21
[b'1' b'2' b'3']


In [ ]:
# indexing
arr = np.array([1,2,3])
arr[0]

1

In [ ]:
# slicing 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[0:2,1:3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [ ]:
# shape and reshape
arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# sum
print(arr)
arr.sum(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [ ]:
# concatenate
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[3,2,3],[4,4,6],[9,8,9]])
np.concatenate((arr1, arr2),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 2, 3],
       [4, 4, 6],
       [9, 8, 9]])

# Pandas

In [ ]:
import pandas as pd

In [ ]:
# creating a series object from list
arr = [1,2,3,4]
d = pd.Series(arr, index=["a","b","c","d"])
d

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# creating a series object from dict
d = {'a': 1, 'b':2, 'c':3}
s = pd.Series(d)
s

a    1
b    2
c    3
dtype: int64

In [ ]:
# creating a dataframe
d = {'Name':['Navaneeth', 'Jishnu', 'Aswin'], 'Marks':[73, 99, 99]}
data = pd.DataFrame(d, index=["s1","s2","s3"])
data

Name  Marks
s1  Navaneeth     73
s2     Jishnu     99
s3      Aswin     99

In [ ]:
# analyzing data
!wget https://www.w3schools.com/python/pandas/data.csv

--2021-09-27 14:40:25--  https://www.w3schools.com/python/pandas/data.csv
Resolving www.w3schools.com (www.w3schools.com)... 192.229.173.207
Connecting to www.w3schools.com (www.w3schools.com)|192.229.173.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2858 (2.8K) [application/octet-stream]
Saving to: ‘data.csv’

data.csv            100%[===================>]   2.79K  --.-KB/s    in 0s      

2021-09-27 14:40:26 (99.8 MB/s) - ‘data.csv’ saved [2858/2858]



In [ ]:
data = pd.read_csv("data.csv")
data

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
data['Duration']

0      60
1      60
2      60
3      45
4      45
       ..
164    60
165    60
166    60
167    75
168    75
Name: Duration, Length: 169, dtype: int64

In [ ]:
np.mean(data['Duration'])

63.84615384615385

In [ ]:
data.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
data.loc[0]

Duration     60.0
Pulse       110.0
Maxpulse    130.0
Calories    409.1
Name: 0, dtype: float64